/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "platform.h"
#include "gpio.h"
#include "timer.h"
#include "uart.h"
#include "ec200u.h"
#include "exti.h"
#include "adc.h"
#include "pwm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char buffer[RX_BUFFER_SIZE];

uint32_t count=0;

uint8_t prev_status = 0;

uint8_t led_status = 1;

uint32_t PWM_val = 0;

int main(void)
{
	gpioa_init(5,OUTPUT);
	gpioa_init(6,OUTPUT);
	gpioc_init(13,INPUT);
	gpioa_adc_init(0);
	tim2_init();
	usart1_init(115200);
	usart2_init(115200);
	//gpiob_pwm_init(0);

	//tim2_interrupt(1000);
	//usart2_rx_interrupt();
	//exti13_init();
	//adc_interrupt();
	//uint8_t prev_status = 1;
	//uint8_t led_status = 1;
	//ec200u_test_with_mqtt();

	usart_tx_str(usart2,"\r\nSTM32 EC200U STARTING...\r\n");


	if (!ec200u_init(usart1))
	{
		usart_tx_str(usart2, "\r\nEC200U INIT FAILED\r\n");
	}

	usart_tx_str(usart2, "\r\nEC200U INIT SUCCESS\r\n");


	/* * First MQTT connection */

	while (!ec200u_mqtt_init(usart1))
	{
		usart_tx_str(usart2,	"\r\nMQTT CONNECTION FAILED\r\n");

	    usart_tx_str(usart2,	"Retrying MQTT...\r\n");

	    tim2_delay(5000);

	}

	usart_tx_str(usart2, "\r\nMQTT INIT SUCCESS\r\n");

//	char topic[128];
//	char message[256];
	while (1)
	{
//****************Toggle led*******************//
//		gpioa_toggle(5);
//		gpioa_toggle(6);
//		tim2_delay(1000);

//******Pin enable and disable*****************//

//		gpioa_digitalWrite(5, HIGH);
//		gpioa_digitalWrite(6, HIGH);
//		usart_tx_uint(usart2, 1);
//		usart_tx_ch(usart2, '\n');
//		usart_tx_str(usart2, "LEDON");
//		usart_tx_ch(usart2, '\n');
//		tim2_delay(1000);
//		gpioa_digitalWrite(5, LOW);
//		gpioa_digitalWrite(6, LOW);
//		usart_tx_uint(usart2, 0);
//		usart_tx_ch(usart2, '\n');
//		usart_tx_str(usart2, "LEDOFF");
//		usart_tx_ch(usart2, '\n');
//		tim2_delay(1000);

//******Receive char data from serial usart2************//
//		if(usart_available(usart2)){
//		char rev_ch = usart_rx_ch(usart2);
//		usart_tx_ch(usart2, rev_ch);
//		usart_tx_ch(usart2, '\n');
//		if(rev_ch=='A')
//		{
//			gpioa_digitalWrite(5, HIGH);
//			gpioa_digitalWrite(6, HIGH);
//			usart_tx_uint(usart2, 1);
//			usart_tx_ch(usart2, '\n');
//			usart_tx_str(usart2, "LEDON");
//			usart_tx_ch(usart2, '\n');
//			tim2_delay(1000);
//		}
//		else if(rev_ch=='B')
//		{
//			gpioa_digitalWrite(5, LOW);
//			gpioa_digitalWrite(6, LOW);
//			usart_tx_uint(usart2, 0);
//			usart_tx_ch(usart2, '\n');
//			usart_tx_str(usart2, "LEDOFF");
//			usart_tx_ch(usart2, '\n');
//			tim2_delay(1000);
//		}
//		else
//		{
//			usart_tx_str(usart2, "Unknown Command");
//		}
//		}

//******Receive string data from serial usart2**********//

//		usart_rx_str(usart2, buffer);
//		usart_tx_str(usart2, "Received:");
//		usart_tx_str(usart2, buffer);
//		usart_tx_ch(usart2, '\n');
//
//		if (strcmp(buffer, "LEDON") == 0)
//		{
//			gpioa_digitalWrite(5, HIGH);
//		    gpioa_digitalWrite(6, HIGH);
//		    usart_tx_str(usart2, "LED IS ON\n");
//		}
//		else if (strcmp(buffer, "LEDOFF") == 0)
//		{
//		    gpioa_digitalWrite(5, LOW);
//		    gpioa_digitalWrite(6, LOW);
//		    usart_tx_str(usart2, "LED IS OFF\n");
//		}
//		else
//		{
//			usart_tx_str(usart2, "Unknown Command");
//		}

//**********Read input pin*********************//

	    uint8_t current_status = gpioc_digitalRead(13);
	    if (current_status != prev_status)
	    {
	        if (!current_status)
	        {
	        	usart_tx_uint(usart2, current_status);
	        	gpioa_digitalWrite(5, led_status);
	        	char output[32];
	        	snprintf(output,sizeof(output),"{\"Button status\":\"%u\"}", (bool)led_status);
	        	ec200u_mqtt_publish(usart1, mqtt_pub_topic, output, 0U, false);
	            (led_status) ? usart_tx_str(usart2, "LED IS ON"):usart_tx_str(usart2, "LED IS OFF");
	            led_status = !led_status;
	            tim2_delay(100);
	        }
	        prev_status = current_status;
	    }

//*********Read analog pin using ADC1**********//

//		uint16_t sensor_data = adc_read();
//		usart_tx_uint(usart2, sensor_data);
//		if(sensor_data > 3000){
//			gpioa_digitalWrite(5, HIGH);
//		}
//		if(sensor_data > 3500){
//			gpioa_digitalWrite(6, HIGH);
//		}
//		if(sensor_data < 3000){
//			gpioa_digitalWrite(5, LOW);
//			gpioa_digitalWrite(6, LOW);
//		}
//		tim2_delay(1000);

//******Write pwm value***********************//

//		PWM_val = usart_rx_uint(usart2);
//		usart_tx_str(usart2, "Received:");
//		usart_tx_uint(usart2, PWM_val);
//	    gpiob_pwm_write(0, PWM_val);
//		tim2_delay(1000);

//		ec200u_mqtt_receive(usart1, topic, message);
//
//		if (strcmp(message, "LEDON") == 0)
//		{
//			gpioa_digitalWrite(5, HIGH);
//			usart_tx_str(usart2, "LED IS ON\r\n");
//		}
//		else if (strcmp(message, "LEDOFF") == 0)
//		{
//			gpioa_digitalWrite(5, LOW);
//			usart_tx_str(usart2, "LED IS OFF\r\n");
//		}

//************************GSM***********************//

		// PC -> GSM
		char ch;

//		/* PC -> GSM */
		if(usart_available(usart2))
		{
		    ch = usart_rx_ch(usart2);

		    usart_tx_ch(usart1, ch);
		}

		/* GSM -> PC */
		if(usart_available(usart1))
		{
		    ch = usart_rx_ch(usart1);

		    usart_tx_ch(usart2, ch);
		}
	}
}
