/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "platform.h"
#include "gpio.h"
#include "timer.h"
#include "uart.h"
#include "exti.h"
#include "adc.h"
#include "pwm.h"
#include <string.h>

char buffer[RX_BUFFER_SIZE];

uint32_t count=0;

uint8_t prev_status = 0;

uint8_t led_status = 0;

uint32_t PWM_val = 0;

int main(void)
{
	gpioa_init(5,OUTPUT);
	gpioa_init(6,OUTPUT);
	gpioc_init(13,INPUT);
	gpioa_adc_init(0);
	tim2_init();
	usart2_init(9600);
	gpiob_pwm_init(0);

	//tim2_interrupt(1000);
	usart2_rx_interrupt();
	//exti13_init();
	//adc_interrupt();
	//uint8_t prev_status = 1;
	//uint8_t led_status = 1;

	while (1)
	{
		//Toggle led

//		gpioa_toggle(5);
//		gpioa_toggle(6);
//		tim2_delay(1000);

		//Pin enable and disable

//		gpioa_digitalWrite(5, HIGH);
//		gpioa_digitalWrite(6, HIGH);
//		tim2_delay(1000);
//		gpioa_digitalWrite(5, LOW);
//		gpioa_digitalWrite(6, LOW);
//		tim2_delay(1000);

		//Read input pin

//	    uint8_t current_status = gpioc_digitalRead(13);
	    //usart2_tx_uint(current_status);
//	    tim2_delay(1000);

		//Transmit char data to serial usart2

//		usart2_tx_ch('A');
//		usart2_tx_ch('\n');
//		tim2_delay(1000);

		//Transmit string data to serial usart2

//		usart2_tx_str("Hello world");
//		usart2_tx_ch('\n');
//		tim2_delay(1000);

		//Transmit int data to serial usart2

//		usart2_tx_uint(120);
//		usart2_tx_ch('\n');
//		tim2_delay(1000);

		//Receive char data from serial usart2

//		char rev_ch = usart2_rx_ch();
//		usart2_tx_ch(rev_ch);
//		usart2_tx_ch('\n');
//		tim2_delay(1000);

		//Receive string  data from serial usart2

//		usart2_rx_str(buffer);
//		usart2_tx_str("Received: ");
//		usart2_tx_str(buffer);
//		usart2_tx_str("\n");
//
//		if (strcmp(buffer, "LEDON") == 0)
//		{
//			gpioa_digitalWrite(5, HIGH);
//		    gpioa_digitalWrite(6, HIGH);
//		    usart2_tx_str("LED IS ON\n");
//		}
//		else if (strcmp(buffer, "LEDOFF") == 0)
//		{
//		    gpioa_digitalWrite(5, LOW);
//		    gpioa_digitalWrite(6, LOW);
//		    usart2_tx_str("LED IS OFF\n");
//		    }
//		else
//		{
//		    usart2_tx_str("Unknown Command\r\n");
//		}

		//Read analog pin using ADC1

//		uint16_t sensor_data = adc_read();
//		usart2_tx_uint(sensor_data);
//		if(sensor_data > 3000){
//			gpioa_digitalWrite(5, HIGH);
//		}
//		if(sensor_data > 3500){
//			gpioa_digitalWrite(6, HIGH);
//		}
//		if(sensor_data < 3000){
//			gpioa_digitalWrite(5, LOW);
//			gpioa_digitalWrite(6, LOW);
//		}
//		tim2_delay(1000);

		//Write pwm value

//		PWM_val = usart2_rx_uint();
//	    usart2_tx_str("Received: ");
//	    usart2_tx_uint(PWM_val);
//	    gpiob_pwm_write(0, PWM_val);
//		tim2_delay(1000);


//	    if (current_status != prev_status)
//	    {
//	        if (!current_status)
//	        {
//	        	gpioa_digitalWrite(5, led_status);
//	            (led_status) ? usart2_tx_str("Led_on\r\n"):usart2_tx_str("Led_off\r\n");
//	            led_status = !led_status;
//	        }
//	        prev_status = current_status;
//	    }
	}
}
