/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.h"
#include "uart.h"
#include "timer.h"

uint32_t count=0;

int main(void)
{
	gpioa_init();
	gpioc_init();
	usart2_init();
	tim2_init();
	while(1){
		if(read_button()){
		     led_on();
		     usart2_tx_str("Pressed\r\n");
		}
		else{
			 led_off();
		}
	}
}
